name: Trigger News Check

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call API endpoint
        run: |
          curl -X GET "https://your-vercel-app.vercel.app/api/check-news?key=${{ secrets.API_SECRET_KEY }}"
